sudo: required
language: node_js
node_js:
  - "9"
services:
  - docker
  - mongodb

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh

install:
  # Tell npm to ignore package-lock.json to avoid making local file
  # changes that would dirty the git workspace.
  - npm config set package-lock false
  - npm install
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - npm test
  # build docker images
  - docker build -t ordenespago .


deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: $HEROKU_APP_NAME
  on: deploy
